version: '3.8'
services:  
  minio:  
    image: quay.io/minio/minio  
    container_name: minio  
    restart: unless-stopped  
    ports:  
    - "9000:9000"
    - "9001:9001"
    volumes:
    - .:/data  
    environment:  
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio124"
    command: server /data --console-address ":9001"
  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432
  cat-app:
    build: ./
    command: ./cat-app
    ports:
      - 8000:8000
    depends_on:
      - db
      - minio
    environment:
      - DB_PASSWORD=qwerty
      - MINIOHOST: minio:9000
      - MINIOUSER: minio
      - MINIOPASS: minio123
