port: "8000"

db:
  username: 'postgres'
  host: 'localhost'
  port: '5436'
  dbname: 'postgres'
  sslmode: 'disable'

minio:
  endpoint: '127.0.0.1:9000'
  accesskeyid: 'minio'
  secretaccesskey: 'minio124'